### ISSUE TITLE
InOut missing/dropped

### ISSUE THREAD

**Issue by iQD** [mash76/particle2dx#3]
Hi there,

First I would like to thank you for your great editor!

Unfortunately I am missing an important feature, which seems it was there in the first place.
Or is it just me and I cannot find it?

May you can explain, why the screenshots and documentation mentions an Import function but it's not there anymore. Instead there is only an Export function.
https://raw.githubusercontent.com/mash76/particle2dx/master/docimg/inout.png
https://github.com/mash76/particle2dx/blob/master/doc.html

Why was it dropped or do you have a release window, when it is coming back?

Do you have any plans to turn it into a desktop app?

Thank you very much in advance!

**Comment by mash76** [comment]
thunk you .  fixed!

**Comment by wouter-willems** [comment]
hi, is there still a way to import? I really need that feature
